### ISSUE TITLE
Not working on VS15 using xunit 

### ISSUE THREAD

**Issue by cottsak** [parthopdas/tddstud10#11]
My project is using xunit 1.9.1 and I'm on VS15 (Microsoft Visual Studio Professional 2015
Version 14.0.24720.00 Update 1). 

I get the question mark in the circle and no other context to why the plugin is apparently not working. Is there a status or log file I can check to get more context?

**Comment by parthopdas** [comment]
Hey @cottsak, thanks for reporting the issue. I am betting this is the same as #2, which I am currently working on. ETA is end of this week.

I am sure of that as I have a hacked up solution in the branch wip-generalize-adapter - where I can run xunit 1.9.1 tests in VS2015.

 w.r.t. logs, you can use the run (as admin) [RealTimeEtwListener](https://github.com/parthopdas/tddstud10/tree/master/RealTimeEtwListener). It captures the logs from tddstudio at realtime.

**Comment by cottsak** [comment]
No worries mate. Ping me when there is a new release and I'll test it out for you.

**Comment by parthopdas** [comment]
Fixed with releave v0.4.5.0.

**Comment by cottsak** [comment]
Installed 0.4.5.0 and I'm still getting the `?` and nothing that looks like my tests are running.

![log results](https://www.dropbox.com/s/sarbxj9mrf8zv69/Screenshot%202016-07-20%2011.37.02.png?dl=1)

**Comment by parthopdas** [comment]
Opened #16 as this is a different issue.
